### ISSUE TITLE
Myget is down

### ISSUE THREAD

**Issue by niemyjski** [loresoft/FluentRest#134]
Myget is completely down and latest packages haven't been pushed to nuget. Can we make nuget the default provider and push existing releases? It seems like myget is dead...

https://www.reddit.com/r/dotnet/comments/159yigd/is_myget_gone_for_good/
https://status.myget.org/

cc @pwelter34

**Comment by ejsmith** [comment]
I'd recommend switching CI builds to feedz.io

**Comment by pwelter34** [comment]
i'll update the build to github actions and push beta packages to github

**Comment by niemyjski** [comment]
Thanks! The latest nightly has been extremely stable for us also :)

**Comment by ejsmith** [comment]
github packages requires auth, it's not a great spot for CI builds

**Comment by pwelter34** [comment]
update to include https://f.feedz.io/loresoft/open/nuget/index.json

**Comment by ejsmith** [comment]
Nice!
