### ISSUE TITLE
Replacing spaces with +

### ISSUE THREAD

**Issue by niemyjski** [loresoft/FluentRest#159]
Is there any specific reason we are doing this: https://github.com/loresoft/FluentRest/blob/7b58509ff36303cdcca74d12008c0f54fdd44748/src/FluentRest/UrlBuilder.cs#L629 This is causing some issues in api calls and it feels like we should just follow the existing behavior and I agree with this https://github.com/dotnet/runtime/issues/45328

**Comment by ssteele** [comment]
+1
I have the same question

**Comment by pwelter34** [comment]
i believe it was just for a cleaner reading url.  i can remove it.

**Comment by pwelter34** [comment]
fixed in v9.9.3

**Comment by niemyjski** [comment]
Thank you!
