### ISSUE TITLE
how to post json

### ISSUE THREAD

**Issue by gatspy** [loresoft/FluentRest#2]
i like this lib,when use  json string to post , I want to how to do？

**Comment by pwelter34** [comment]
To post JSON, use the Content method.  You can change the serializer by implementing the `IContentSerializer` interface.  The default implementation is `JsonContentSerializer`

```c#
var user = UserData.Create();
var client = CreateClient();

var result = await client.PostAsync<EchoResult>(b => b
    .AppendPath("post")
    .QueryString("page", 10)
    .Content(user)
);
```
