### ISSUE TITLE
Response Errors

### ISSUE THREAD

**Issue by jellymark** [loresoft/FluentRest#3]
Hi 

How would you recommend handling a response error with Automatic deserialization of responses?

Thanks in advance.

Love the project!

**Comment by pwelter34** [comment]
You can get the response before deserialization, then check the response code.

    var client = CreateClient();

    var response = await client.PostAsync(b => b
        .AppendPath("post")
        .FormValue("Test", "Value")
        .FormValue("key", "value")
        .QueryString("page", 10)
    );

    if (response.StatusCode != HttpStatusCode.OK );
        return;
        
    var result = await response.DeserializeAsync<EchoResult>();

**Comment by jellymark** [comment]
Thanks for this Paul
