### ISSUE TITLE
Send Post over https

### ISSUE THREAD

**Issue by hgrojas** [loresoft/FluentRest#5]
I need to encode in C # the following:

POST https://pepep.test.com/apiAuthV1/auth HTTP/1.1

Accept-Encoding: gzip,deflate
Content-Type: application/x-www-form-urlencoded
Authorization: Basic Y1QwcDF5clRBZehstrhjfufk77878SZzE4RERXN1lBS2hJU1R6ZzVpUHc=

grant_type=password&username=argentina&password=1234567

**Comment by pwelter34** [comment]
This should work

```c#
var client = new FluentClient();

var result = await client.PostAsync(b => b
    .BaseUri("https://pepep.test.com/apiAuthV1/")
    .AppendPath("auth")
    .FormValue("grant_type", "password")
    .FormValue("username", "argentina")
    .FormValue("password", "1234567")
    .Header(h => h.Authorization("Basic", "Y1QwcDF5clRBZehstrhjfufk77878SZzE4RERXN1lBS2hJU1R6ZzVpUHc="))
);
```

**Comment by hgrojas** [comment]
And if I have to add a certificate .cer, how would it be?

**Comment by hgrojas** [comment]
I detected the following: if you pass through the contructor the handler:

Var fClient = new FluentClient (serializer, handler);

  Does not set the handler, but if you use:

FluentClient.Create (x =>
             {
                 X.HttpHandler (handler)
                 .Serializer (new JsonContentSerializer ());
             });

Now set the handler
